### ISSUE TITLE
[BUG]: Vercel not recognizing the routes

### ISSUE THREAD

**Issue by LelouchFR** [LelouchFR/skill-icons#1]
### Description of the bug

X

### Steps To Reproduce

X

**Comment by LelouchFR** [comment]
@hawl1 isnt that still a thing ?

The link for example https://go-skill-icons.vercel.app/icons?i=go is giving back a 404 :/

**Comment by NonsensicalOne** [comment]
> @hawl1 isnt that still a thing ?
> 
> The link for example https://go-skill-icons.vercel.app/icons?i=go is giving back a 404 :/

after forking around, i found out that actions doesnt deploy to production :sob:
https://github.com/LelouchFR/skill-icons/blob/main/.github/workflows/deploy.yml
replace the line 28 (run: vercel deploy --token=${{ secrets.VERCEL_TOKEN }})
with `run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}` and then it should work
by the way its not on /icons its on /api/icons

**Comment by NonsensicalOne** [comment]
@LelouchFR response pls

**Comment by LelouchFR** [comment]
Yes I'm going to look forward into that after finishing to eat :D

**Comment by LelouchFR** [comment]
well, idk why but we're back at this build error :/ when trying to run the command

**Comment by NonsensicalOne** [comment]
> well, idk why but we're back at this build error :/ when trying to run the command

well, u didnt changed the actions file
![image](https://github.com/LelouchFR/skill-icons/assets/126889064/46e2a20d-0c1d-42f2-99ac-4629a7dbe997)
it doesnt have the --prod argument

**Comment by LelouchFR** [comment]
finally ![](https://go-skill-icons.vercel.app/api/icons?i=go) !!!!
