### ISSUE TITLE
[BUG]: README.md

### ISSUE THREAD

**Issue by RushilJalal** [LelouchFR/skill-icons#106]
### Description of the bug

This screenshot will explain everything
As you can see, the Support Project heading is out of alignment
Kindly fix it.

![image](https://github.com/LelouchFR/skill-icons/assets/54212357/bc9bbd43-4799-4f36-b705-abb6ccfa0fb4)

### Steps To Reproduce

1. Go to https://github.com/LelouchFR/skill-icons
2. Scroll down to the README
3. Observe

### Additional Information

I can work on the issue if you like.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
@RushilJalal I is not a bug... but since a lot of person don't like that way, I'm going to change it then.
