### ISSUE TITLE
[NEW ICON]: Steam

### ISSUE THREAD

**Issue by byeoon** [LelouchFR/skill-icons#109]
### Skill Name

Steam

### Why?

I'm developing a website and skillicons is a very creative way to add image links without having to use any external services like bootstrap icons, fontawesome, etc. It also helps me avoid needing to download every image and have some weird offset, and overall just makes it simpler.
(Example:)
![image](https://github.com/LelouchFR/skill-icons/assets/47872200/71ebda52-65d9-4bdc-b669-846e91fd1045)

### Reference Image

https://en.m.wikipedia.org/wiki/File:Steam_icon_logo.svg

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
#117
