### ISSUE TITLE
[FEAT]: Ability to set theme=auto for automatic theme switching based on what user set in browser

### ISSUE THREAD

**Issue by shreyas-a-s** [LelouchFR/skill-icons#11]
### Description

Currently it is only possible to set theme to either `dark` or `light` and if we set theme to dark, anybody who is looking at the readme from a "light themed" browser might feel the icons to be detached from the overall theme of browser and vice versa.

Hence it would be nice to have the option to set `theme=auto` and the theme is set to the one which user has set in their browser.

Websites do this by using [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) property of css. And I am currently doing something like the code below in my readme for getting the desired behaviour.

```md
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/25423296/163456776-7f95b81a-f1ed-45f7-b7ab-8fa810d529fa.png">
  <source media="(prefers-color-scheme: light)" srcset="https://user-images.githubusercontent.com/25423296/163456779-a8556205-d0a5-45e2-ac17-42d089e3c3f8.png">
  <img alt="Shows an illustrated sun in light mode and a moon with stars in dark mode." src="https://user-images.githubusercontent.com/25423296/163456779-a8556205-d0a5-45e2-ac17-42d089e3c3f8.png">
</picture>
```

But this requires one to create the svg files for both dark and light modes and update the readme with those newer svg files whenever he/she wants to add/remove an icon and it's a bit tedious. Hence it would be great to get an option to set theme to `auto`.

### Additional Information

This is the same [issue](https://github.com/tandpfun/skill-icons/issues/927) as open in the [other](https://github.com/tandpfun/skill-icons/issues/927) skill-icons repo.

**Comment by LelouchFR** [comment]
I theory-crafted something, but I don't know it is that efficient and possible to make (or is just going to take a lot of time).

The fact that we can add styles using the style tag in a svg is very usefull (seen in this [article](https://blog.tomayac.com/2019/09/21/prefers-color-scheme-in-svg-favicons-for-dark-mode-icons/)), but can get a lot out of hand for hard and complex icons.

Since the response of the api isnt `html`, but `image/svg+xml`, we can't implement something like you said and return html... I think it would be okay to work with css directly into them and create a `icon-auto.svg` file for those icons and  make it work like another theme, just like light and dark works, but this would **increase the number of svg very fast** I guess. Would create also a lot of work for people creating those icons.

Going to continue working on the question and try to make something that works as intended.

It may take a lot time, since it means making back all the icons kinda "from scratch".

**Comment by shreyas-a-s** [comment]
Hi @LelouchFR,

It's really cool reading about the *something* you've theorized. It's a pretty interesting way of modifying an svg. Thanks for letting me know about that. I didn't know about the possibility of using @media queries in github readme up until last week and now this, man I am loving the open-souce community.

Now coming back to our situation, I think it would be wise not to use this method due to the reasons you've mentioned. That is,

1. It means an extra icon for literally every app/program and that is currently in the repo
2. Plus an extra icon for any new icon that gets added.

That to me feels like too much work especially since the feature is so niche and due to the fact that the coding aspect of it is a bit harder from my testing.

So I think we should dive deeper into this rabbit hole little by little as we get time. Thereby learning more and more about things like this `style-in-svg` trying to find a better way of implementing this feature.

What do you think?

**Comment by LelouchFR** [comment]
Hey @shreyas-a-s !
I've done a branch where I'm currently making every icon that has a dark & light theme have a auto theme, right now, only done all from a to c (included), but I think I'm getting the hand of it, but I just don't know if it works 💀

I just know it works by switching on directly from file, but idk if it takes the theme in count when parsed on using the api, going to look into that after I've done all of them... started, want to finish

**Comment by shreyas-a-s** [comment]
Yo man, what can I say! You - Are - a - Determined - Person, and I love that. To be honest, if I were in your place, I would have been looking for another way of achieving the same due to the shear number of icons to reconstruct. Hats off to you, man. 👌🏻

I really want to help you with some icons but due to exams I don't have much time. But if there's anything I can do like testing and stuff, please tell. I would me more than happy to be part of this process. 🚀

I have tested some icons by opening the raw file from github and changing my browsers theme. Changing the theme do automatically change the icons theme also. So I think it's working. 🎉

**Comment by LelouchFR** [comment]
@shreyas-a-s Finally done! it has been very long to do, but it's now live :D

**Comment by shreyas-a-s** [comment]
237 files changed. 7,638 Additions. 318 Deletions. Wow! Hats off again @LelouchFR. You are awesome, man. 🚀 I cant wait to try it.

**Comment by alvinsjoy** [comment]
Awsome! 🎉
