### ISSUE TITLE
[NEW ICON]: Twitch

### ISSUE THREAD

**Issue by byeoon** [LelouchFR/skill-icons#110]
### Skill Name

Twitch

### Why?

Same reason as #109, and also since YouTube already exists, I think Twitch should also be here as well.

### Reference Image

https://www.vectorlogo.zone/logos/twitch/twitch-tile.svg 
(literally perfect icon for this)

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
#117
