### ISSUE TITLE
[NEW ICON]: Hugo

### ISSUE THREAD

**Issue by NonsensicalOne** [LelouchFR/skill-icons#113]
### Skill Name

Hugo

### Why?

Hugo is a very popular static site generator

### Reference Image

dunno which one is better

The H only
![Group 1](https://github.com/LelouchFR/skill-icons/assets/126889064/848d7f0e-68fc-4e99-a42c-f861bc865397)
Full logo
![hugo-logo-wide](https://github.com/LelouchFR/skill-icons/assets/126889064/47e1891e-b86f-4d74-98c1-7bd899bf3c96)

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
#117
