### ISSUE TITLE
[NEW ICON]: Alternate Twitter Icon

### ISSUE THREAD

**Issue by byeoon** [LelouchFR/skill-icons#118]
### Skill Name

Twitter (alt)

### Why?

I'd rather show the Twitter icon than the X icon and I think having a separate version would be nice (I HATE Elon!!!)

### Reference Image

https://www.vectorlogo.zone/logos/twitter/twitter-tile.svg

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
I don't really like the idea of creating a duplicate :/ I don't really think I'm going to change it. Let's just say we move forward.

**Comment by byeoon** [comment]
> I don't really like the idea of creating a duplicate :/ I don't really think I'm going to change it. Let's just say we move forward.

Sounds good to me

**Comment by UMMAN2005** [comment]
If you really want to use twitter, you can use this url:

https://skillicons.dev/icons?i=twitter

[![Twitter](https://skillicons.dev/icons?i=twitter)](https://x.com/<your_username>)

**Comment by LelouchFR** [comment]
@byeoon you can kinda combine the 2 using the img tag like that (but plz try not to add it in the middle, else it would do 2 api calls for one line :/) :

```html
<img src="https://skillicons.dev/icons?i=twitter"/><img src="https://go-skill-icons.vercel.app/api/icons?i=github,steam"/>
```
which gives that:
<img src="https://skillicons.dev/icons?i=twitter"/><img src="https://go-skill-icons.vercel.app/api/icons?i=github,steam"/>
