### ISSUE TITLE
[NEW ICON] Assembly

### ISSUE THREAD

**Issue by UMMAN2005** [LelouchFR/skill-icons#12]
### Skill Name

Assembly

### Why?

It is very popular in low level programming!

### Reference Image

https://cdn.hackr.io/uploads/topics_svg/1515163329FBBk5SGRAt.svg

**Comment by LelouchFR** [comment]
I have done like a v1, but I'm not really sure of the light theme one... Actually should there be a light one for this one, since like, for example, webassembly does not have one ?

![image](https://github.com/LelouchFR/skill-icons/assets/75901978/ac727947-0387-442c-9d38-daa5222f0df8)

**Comment by UMMAN2005** [comment]
I think that, left one is enough. White look a little bit weird to me

**Comment by LelouchFR** [comment]
Yeah I agree, I think if there is changes that has to be done about this, it can be done in the future
