### ISSUE TITLE
How to add Cloud provider tools in the icon list  ?

### ISSUE THREAD

**Issue by Francois-lenne** [LelouchFR/skill-icons#123]
### Description

Hi,

Today cloud provider are often use by company and dev.elopers  But inside those cloud provider there is SaaS and PaaS tools for exemple in AWS with redhsift, S3, EC2 ... 

Have you thinking of a synthax   @LelouchFR   in order to add those icon  tools in this repository uniformly ?

Thanks in advance,
François

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by josemateuss** [comment]
Redshift already exists in the project.

**Comment by Francois-lenne** [comment]
@josemateuss  ok thanks for your reply so we call it by the name they have (i was thinking by add Lambda, bigquery ....)

**Comment by LelouchFR** [comment]
Yeah @Francois-lenne I think we will stick with just their name, since it takes off a layer of difficulty for just an icon (if we add something like aws-lambda instead of just lambda).
