### ISSUE TITLE
[NEW ICON]: X (twiiter

### ISSUE THREAD

**Issue by zougari47** [LelouchFR/skill-icons#134]
### Skill Name

X

### Why?

I saw LinkedIn icon and I say why not X

### Reference Image

You can download the SVG from the official [website](https://about.x.com/en/who-we-are/brand-toolkit)

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by ghost** [comment]
already available: https://go-skill-icons.vercel.app/api/icons?i=x

<img src="https://go-skill-icons.vercel.app/api/icons?i=x" />

**Comment by zougari47** [comment]
My bad didn't notice it👍
