### ISSUE TITLE
[NEW ICON] IntelliJ IDEA

### ISSUE THREAD

**Issue by LucasWithBoots** [LelouchFR/skill-icons#136]
### Skill Name

IntelliJ IDEA

### Why?

IntelliJ IDEA is an Integrated Development Environment (IDE) for Java and Kotlin. Widely used worldwide and is part of the Jetbrains group.

There are two versions available, free (community) and paid (ultimate). I think there should be both options.

### Reference Image

![image](https://github.com/LelouchFR/skill-icons/assets/111355335/578675e9-59b2-45f4-b8b6-ddb38dd26485)
![image](https://github.com/LelouchFR/skill-icons/assets/111355335/ef62d604-544d-4b10-910e-fa0798ea068d)

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
@LucasWithBoots The icon is already in the project, to use it you just have to use the word `idea`in the link. Please read the contributing guidelilnes before opening an issue
