### ISSUE TITLE
[BUG]: Digital Ocean Icon not working

### ISSUE THREAD

**Issue by eng-gabrielscardoso** [LelouchFR/skill-icons#138]
### Description of the bug

When try to retrieve Digital Ocean icon nothing returns

![image](https://github.com/LelouchFR/skill-icons/assets/67348001/7d417132-7847-46a6-9b92-a709352f3bb5)

### Steps To Reproduce

1. Go to API and type to get Digital Ocean icon
![image](https://github.com/LelouchFR/skill-icons/assets/67348001/eb13eb6d-688e-482e-a133-0008bf037beb)

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
I found the issue, there's no auto icon for it, this is what it's causing it to not work, going to fix this asap
