### ISSUE TITLE
[NEW ICON]: Inkscape

### ISSUE THREAD

**Issue by aerocyber** [LelouchFR/skill-icons#153]
### Skill Name

Inkscape

### Why?

Inkscape is a popular SVG editor. Adding it would be beneficial to show off Inkscape skills.

### Reference Image

![inkscape](https://github.com/LelouchFR/skill-icons/assets/86760749/e09c3630-d184-42bf-98f9-be8bbca7312f)

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by Daynlight** [comment]
![inkscape-dark](https://github.com/LelouchFR/skill-icons/assets/62157770/acacb4cd-f09a-47b8-8e5f-93ec6a012be3)
![inkscape-light](https://github.com/LelouchFR/skill-icons/assets/62157770/462665fa-3634-4a77-898a-73a6dd30a2e0)
