### ISSUE TITLE
[NEW ICON]: Podman & LXD

### ISSUE THREAD

**Issue by NonsensicalOne** [LelouchFR/skill-icons#155]
### Skill Name

Podman & LXC

### Why?

They are good alternatives to docker

### Reference Image

![Containers](https://linuxcontainers.org/static/img/containers.svg)
![Podman](https://icon.icepanel.io/Technology/svg/Podman.svg)

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by Daynlight** [comment]
![podman-dark](https://github.com/LelouchFR/skill-icons/assets/62157770/654b5d16-427e-4688-b5b9-f82e7578017b)
![podman-light](https://github.com/LelouchFR/skill-icons/assets/62157770/781e5d5d-1238-4aff-b3fb-00493fabefbf)
![lxc-dark](https://github.com/LelouchFR/skill-icons/assets/62157770/bd809119-f5a9-49df-8a1d-8ce479958422)
![lxc-light](https://github.com/LelouchFR/skill-icons/assets/62157770/be760eb7-8f65-4ab4-aec7-078b34abacb0)
