### ISSUE TITLE
[NEW ICON]: Jupyter Notebook, Github Pages, Render, GSAP, Streamlit

### ISSUE THREAD

**Issue by Sudhanshu-Ambastha** [LelouchFR/skill-icons#156]
### Skill Name

Jupyter Notebook, Github Pages, Render & GSAP

### Why?

Jupyter notebook is still used for ml or ai
just like GitHub actions why not GitHub pages
Render is also used as deployment platform
GSAP is widely used as JavaScript library for animation
Streamlit used for deploying Python models

### Reference Image

![github pages](https://github.com/tandpfun/skill-icons/assets/135802131/43df0ee9-fb75-4736-93ca-686f970df87e)

![jupyter notebook](https://github.com/tandpfun/skill-icons/assets/135802131/e7045bcc-aeba-4b11-a34f-8c650f1dbe68)

![Render (1)](https://github.com/tandpfun/skill-icons/assets/135802131/0a555790-498f-4a6c-8b25-619f6f4c2dc1)

![GSAP](https://github.com/LelouchFR/skill-icons/assets/135802131/e2c10b39-5cd5-4c82-b16c-1b0964fa8a07)

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by Daynlight** [comment]
![jupyter-auto](https://github.com/LelouchFR/skill-icons/assets/62157770/43e9d27f-b43f-46a6-8459-d9cd3db1a95d)
![jupyter-dark](https://github.com/LelouchFR/skill-icons/assets/62157770/1a0047ac-9ec9-4f18-bd44-71055f889e06)
![jupyter-light](https://github.com/LelouchFR/skill-icons/assets/62157770/49d9bab5-3c8a-44eb-be24-79b4500f8fea)

**Comment by Daynlight** [comment]
![render-auto](https://github.com/LelouchFR/skill-icons/assets/62157770/3b06df31-de30-4e40-9750-deaa8bd5c344)
![render-dark](https://github.com/LelouchFR/skill-icons/assets/62157770/6fc0527c-03af-4dba-9f8f-a5a687c95fbf)
![render-light](https://github.com/LelouchFR/skill-icons/assets/62157770/69c570f0-7ea8-4bad-894e-b224828d9764)

**Comment by Daynlight** [comment]
![githubpages-auto](https://github.com/LelouchFR/skill-icons/assets/62157770/d2534c28-4652-4f5e-a866-1f228aa79cca)
![githubpages-dark](https://github.com/LelouchFR/skill-icons/assets/62157770/46a9a3b2-2183-4934-86fd-5f65f904036a)
![githubpages-light](https://github.com/LelouchFR/skill-icons/assets/62157770/d6e39302-4fd1-449b-b83e-a0da52b972e0)

**Comment by Sudhanshu-Ambastha** [comment]
![GSAP](https://github.com/LelouchFR/skill-icons/assets/135802131/940e125b-7b5c-41ac-af13-b28292f9ebc8)

Here it is for GSAP also add this one

**Comment by Daynlight** [comment]
![gsap-auto](https://github.com/LelouchFR/skill-icons/assets/62157770/0889eb49-9540-4dae-9cdd-3987725e3ece)
Alredy exist

**Comment by Sudhanshu-Ambastha** [comment]
![Streamlit](https://github.com/user-attachments/assets/48d46aa0-8c1a-46c6-8253-8c0ea9e32aca)

Streamlit used for deploying Python models
Also add this one
