### ISSUE TITLE
[NEW ICON]: Jekyll 

### ISSUE THREAD

**Issue by JuanPabloDiaz** [LelouchFR/skill-icons#157]
### Skill Name

Jekyll

### Why?

Jekyll is a static site generator written in Ruby by Tom Preston-Werner. It is distributed under the open-source MIT license

### Reference Image

![](https://raw.githubusercontent.com/Snailedlt/devicon/19019de2120a787c771b0b83a72752912e0cd598/icons/jekyll/jekyll-original-wordmark.svg)

![](https://raw.githubusercontent.com/Snailedlt/devicon/19019de2120a787c771b0b83a72752912e0cd598/icons/jekyll/jekyll-original.svg)
 
![](https://raw.githubusercontent.com/Snailedlt/devicon/19019de2120a787c771b0b83a72752912e0cd598/icons/jekyll/jekyll-plain-wordmark.svg)

![](https://raw.githubusercontent.com/Snailedlt/devicon/19019de2120a787c771b0b83a72752912e0cd598/icons/jekyll/jekyll-plain.svg)

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by Daynlight** [comment]
![jekyll-auto](https://github.com/LelouchFR/skill-icons/assets/62157770/e6bcc76e-14c5-4326-99cc-e71218481ada)
![jekyll-dark](https://github.com/LelouchFR/skill-icons/assets/62157770/e88b4931-1c6d-4840-a15a-5754fcc161ff)
![jekyll-light](https://github.com/LelouchFR/skill-icons/assets/62157770/60b95140-b83e-4cbd-94f6-108cfd1addf2)

**Comment by JuanPabloDiaz** [comment]
In this repo, things move quick!

same as in the other one lol

**Comment by JuanPabloDiaz** [comment]
Just curious, how do you create the icons? I would like to contribute and design one myself.

**Comment by LelouchFR** [comment]
> Just curious, how do you create the icons? I would like to contribute and design one myself.

You may want to read the [contributing guidelines](https://github.com/LelouchFR/skill-icons/blob/089339d13ba4647b35374048595423975150d7b4/.github/CONTRIBUTING.md#contributing-to-the-project), if you get stuck because some lack of precisions, you can ask us ;)
