### ISSUE TITLE
[NEW ICON]: Open Source

### ISSUE THREAD

**Issue by JuanPabloDiaz** [LelouchFR/skill-icons#160]
### Skill Name

Open Source

### Why?

code is open source

I found this [issue](https://github.com/FortAwesome/Font-Awesome/issues/12092) :smil

### Reference Image

![](https://user-images.githubusercontent.com/28990589/34908095-57a48cce-f83f-11e7-87d2-7579d0be5740.jpg)

![](https://th.bing.com/th/id/R.f9f1cb74dac8625ac6da844a1473d436?rik=QQYBwgiaJBm5VA&pid=ImgRaw&r=0)

![](https://th.bing.com/th/id/R.a5c51c41e3bedec6a10eccdb90e431bb?rik=difhjtS8%2bmBtSA&pid=ImgRaw&r=0)

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by Daynlight** [comment]
![opensource-auto](https://github.com/LelouchFR/skill-icons/assets/62157770/387c96f8-dbcd-4469-af1c-74ad5d796133)
![opensource-dark](https://github.com/LelouchFR/skill-icons/assets/62157770/635a105a-856b-4b8d-8fe2-fa2e6bf65383)
![opensource-light](https://github.com/LelouchFR/skill-icons/assets/62157770/8c961039-61ce-49d6-86fc-5e87e9bd57c6)

**Comment by JuanPabloDiaz** [comment]
Thank you
