### ISSUE TITLE
[NEW ICON]: ElementPlus, Tomcat, SpringBoot. PrimeVue, PM2, PLSQL, OracleDB 

### ISSUE THREAD

**Issue by ghost** [LelouchFR/skill-icons#163]
### Skill Name

ElementPlus, Tomcat, SpringBoot. PrimeVue, PM2, PLSQL, OracleDB 

### Why?

Hello
First of all, thank you so much for creating a new project yourself like this because the update is not old in the previous version. I'm using it well!

To get to the point, I'd like to suggest creating icons for the stacks I wrote in the title earlier.

The reason is that all the stacks you've written are technologies that are widely used worldwide and are still loved.
Thank you very much :)

If I have time, I would like to make it myself and give it to you

We ask for your positive review.

### Reference Image

![ElementPlus](https://github.com/LelouchFR/skill-icons/assets/150807232/2d5d56c2-ea2a-45e6-9441-37d1e236617e)

![PM2](https://github.com/LelouchFR/skill-icons/assets/150807232/5825c6f4-d1d6-45ed-a2c5-caf5c3f40b43)

![SpringBoot](https://github.com/LelouchFR/skill-icons/assets/150807232/fd491469-9b28-4eb3-b9bc-b02812ac14a1)

![OracleDB](https://github.com/LelouchFR/skill-icons/assets/150807232/696b245e-0adb-4328-abf9-d25ae7edf007)

![PLSQL](https://github.com/LelouchFR/skill-icons/assets/150807232/908bb757-3680-45c7-97c8-47fa36c55b8f)

![Tomcat](https://github.com/LelouchFR/skill-icons/assets/150807232/a2c95603-f674-4dc9-a982-ee84acf1d16a)

### Code of Conduct Acknowledgment

- [x] I have read and agree to the Code of Conduct.

**Comment by Daynlight** [comment]
![spring-dark](https://github.com/LelouchFR/skill-icons/assets/62157770/14127a33-eea0-47aa-b4e0-ac8e3223ad69)
![spring-light](https://github.com/LelouchFR/skill-icons/assets/62157770/8640419a-6747-4c9d-9d72-e45046f82176)
Spring boot exist

**Comment by Daynlight** [comment]
![elementplus-auto](https://github.com/LelouchFR/skill-icons/assets/62157770/194c0fa8-662b-497d-af29-3a22f2e7e29a)
![elementplus-dark](https://github.com/LelouchFR/skill-icons/assets/62157770/59854aa3-c1ab-429e-b6e0-8ae59f1ce714)
![elementplus-light](https://github.com/LelouchFR/skill-icons/assets/62157770/5e6001f1-508d-4078-8ad0-790925988a30)

**Comment by Daynlight** [comment]
![tomcat-auto](https://github.com/LelouchFR/skill-icons/assets/62157770/24e800c6-af63-40dd-ab44-46b0a075a97d)
![tomcat-dark](https://github.com/LelouchFR/skill-icons/assets/62157770/ee14c8b9-0926-4ed4-897e-1b9565f32d65)
![tomcat-light](https://github.com/LelouchFR/skill-icons/assets/62157770/bdb33eb7-d3fa-4c01-8385-e3dc3a42c830)

**Comment by Daynlight** [comment]
![primevue-auto](https://github.com/LelouchFR/skill-icons/assets/62157770/ca4b69f9-806f-430b-ba46-f39ce6b0bea3)
![primevue-dark](https://github.com/LelouchFR/skill-icons/assets/62157770/c22c0a3f-e818-4d75-afa8-9ed8f10d8cc9)
![primevue-light](https://github.com/LelouchFR/skill-icons/assets/62157770/e62e1615-b6ca-475d-a3e5-994743f24ad6)

**Comment by Daynlight** [comment]
![pm2-auto](https://github.com/LelouchFR/skill-icons/assets/62157770/d3a8b91f-cb51-47d8-a3eb-1e7f4af416f5)
![pm2-dark](https://github.com/LelouchFR/skill-icons/assets/62157770/83404eb3-e063-4944-96f4-0d398e2457a4)
![pm2-light](https://github.com/LelouchFR/skill-icons/assets/62157770/985f669c-eebb-454c-bcb2-02d352d28ba2)

**Comment by Daynlight** [comment]
![plsql-auto](https://github.com/LelouchFR/skill-icons/assets/62157770/c468439d-69ff-44ae-ac53-a7797b2a920e)
![plsql-dark](https://github.com/LelouchFR/skill-icons/assets/62157770/6ab390f3-ecf9-4493-a161-cbb55fbb1545)
![plsql-light](https://github.com/LelouchFR/skill-icons/assets/62157770/1575aa90-4468-4947-b051-c7101ca8e6a4)

**Comment by Daynlight** [comment]
![oracledb-auto](https://github.com/LelouchFR/skill-icons/assets/62157770/122e12f4-46c7-4609-bcee-697191d316e2)
![oracledb-dark](https://github.com/LelouchFR/skill-icons/assets/62157770/a2750b5b-5bca-40a6-b75d-3d2bc40eacdd)
![oracledb-light](https://github.com/LelouchFR/skill-icons/assets/62157770/74860289-8d61-4bcf-8490-465b88c07945)

**Comment by ghost** [comment]
Very Very Thank You !
