### ISSUE TITLE
[NEW ICON]: API

### ISSUE THREAD

**Issue by JuanPabloDiaz** [LelouchFR/skill-icons#164]
### Skill Name

API

### Why?

It will be nice to have an icon that represents API. 

I see there is one for FastAPI but not just API

### Reference Image

<img src="https://clipground.com/images/api-clipart-png-8.jpg" />

<img src="https://johnjayrec.nyc/wp-content/uploads/2016/02/logo_api.png" />

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by Daynlight** [comment]
![api-auto](https://github.com/LelouchFR/skill-icons/assets/62157770/bc92df4a-5f45-4384-8118-e5763b6065ab)
![api-dark](https://github.com/LelouchFR/skill-icons/assets/62157770/ade3d16e-d10c-489c-9fe3-96b793038165)
![api-light](https://github.com/LelouchFR/skill-icons/assets/62157770/f8643fc4-2d29-4446-9818-0fc265c8d984)
