### ISSUE TITLE
[NEW ICON]: Windows Terminal

### ISSUE THREAD

**Issue by JuanPabloDiaz** [LelouchFR/skill-icons#165]
### Skill Name

Terminal 

### Why?

windows terminal / shell

different than powershell

### Reference Image

![image](https://github.com/LelouchFR/skill-icons/assets/25883220/ddb023f1-6fbd-4dfc-9863-f5d6ccd44027)![terminal-logos](https://github.com/microsoft/terminal/assets/91625426/333ddc76-8ab2-4eb4-a8c0-4d7b953b1179)

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by Daynlight** [comment]
![terminal-auto](https://github.com/LelouchFR/skill-icons/assets/62157770/9f39f694-5118-43f8-99ab-4788e5c437c4)
![terminal-dark](https://github.com/LelouchFR/skill-icons/assets/62157770/58ef5115-5458-498c-a141-92899e4870d7)
![terminal-light](https://github.com/LelouchFR/skill-icons/assets/62157770/01d759cd-b2a9-4a9a-8b52-4ecd0ff0d090)
