### ISSUE TITLE
[NEW ICON]: Lighthouse

### ISSUE THREAD

**Issue by JuanPabloDiaz** [LelouchFR/skill-icons#166]
### Skill Name

Lighthouse

### Why?

[Lighthouse](https://github.com/GoogleChrome/lighthouse) is an open-source, automated tool for improving the quality of web pages. You can run it against any web page, public or requiring authentication. It has audits for performance, accessibility, progressive web apps, SEO, and more.

### Reference Image

![](https://developer.chrome.com/static/docs/lighthouse/overview/image/lighthouse-logo-3c45f51ca8cfc.svg)

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by Daynlight** [comment]
![lighthouse](https://github.com/LelouchFR/skill-icons/assets/62157770/ddbc87a8-da6a-45d6-88cd-abc58a935dbb)
