### ISSUE TITLE
[NEW ICON]: LlamaIndex

### ISSUE THREAD

**Issue by simonwei97** [LelouchFR/skill-icons#168]
### Skill Name

LlamaIndex

### Why?

[LlamaIndex (GPT Index)](https://github.com/run-llama/llama_index) is a **Open-Source** data framework for your LLM application. Building with LlamaIndex typically involves working with LlamaIndex core and a chosen set of integrations (or plugins).

### Reference Image

<img src="https://github.com/LelouchFR/skill-icons/assets/119845914/73f1cd88-2251-4378-9472-67e0ea6faa97" width=40%>
<img src="https://github.com/LelouchFR/skill-icons/assets/119845914/05f4cdb2-d619-4df5-9686-314f096985a7">

- LlamaIndex White Image: https://github.com/run-llama/logos/blob/main/LlamaLogoWhite.png
- LlamaIndex Square Black SVG: https://github.com/run-llama/logos/blob/main/LlamaSquareBlack.svg

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by Daynlight** [comment]
![llamaindex-auto](https://github.com/LelouchFR/skill-icons/assets/62157770/287e0d9b-7c7f-41db-aa60-b39e7540fa40)
![llamaindex-dark](https://github.com/LelouchFR/skill-icons/assets/62157770/29b811ba-0255-4b82-bd86-92b7c9d27138)
![llamaindex-light](https://github.com/LelouchFR/skill-icons/assets/62157770/ce5a5481-8d38-4694-9d2b-bc7aff9f84c4)
