### ISSUE TITLE
[FEAT]: main web page

### ISSUE THREAD

**Issue by Rapter001** [LelouchFR/skill-icons#173]
### Description

Make a main web page for the https://go-skill-icons.vercel.app website idk if its a error but i think you just don't have a main web page

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by ghost** [comment]
> ### Description
> Make a main web page for the https://go-skill-icons.vercel.app website idk if its a error but i think you just don't have a main web page
> 
> ### Additional Information
> _No response_
> 
> ### Code of Conduct Acknowledgment
> * [x]  I have read and agree to the Code of Conduct.

it's not an error, currently main website is under development when it's done it will be released, you can find more here #101

**Comment by LelouchFR** [comment]
duplicate of #101
