### ISSUE TITLE
[NEW ICON]: Elastic (ELK Stack all Icons )

### ISSUE THREAD

**Issue by PritamChk** [LelouchFR/skill-icons#178]
### Skill Name

ELK stack - monitoring tools

### Why?

ELK stack is widely used in industry for monitoring purposes
https://www.elastic.co/elastic-stack

### Reference Image

<img width="958" alt="image" src="https://github.com/user-attachments/assets/1d621267-3856-44d3-bd60-1b6def0f0cec">

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by ItsJoshBrown** [comment]
@PritamChk  submitted a PR for these, Elasticsearch is already an icon in the repository though so I added the other 2.

**Comment by PritamChk** [comment]
> @PritamChk submitted a PR for these, Elasticsearch is already an icon in the repository though so I added the other 2.

Thanks !!!
