### ISSUE TITLE
[NEW ICON]: Add SonarQube icon

### ISSUE THREAD

**Issue by PritamChk** [LelouchFR/skill-icons#179]
### Skill Name

Sonarqube

### Why?

it is used in industry to scan code quality

### Reference Image

![image](https://github.com/user-attachments/assets/b39a7f39-2de1-4ac8-bfc0-aa3b5b7020c2)

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
@PritamChk By seeing the logos, I don't really like their design, but what could be better, is just to add their main logo, which would be better I think for this purpose, what do you think ?

![the main logo](https://assets-eu-01.kc-usercontent.com/b1ac63b6-1e65-01f4-6f38-e97c0e9214a1/aedb7b5e-8556-4840-a69c-bce396891b0e/sonar-logo-horizontal-dark-bg.svg?w=170&h=42&auto=format&fit=crop)

**Comment by PritamChk** [comment]
Yeah this looks good, but people who are using it they might be often more familiar with the official logo.

**Comment by PritamChk** [comment]
> @PritamChk By seeing the logos, I don't really like their design, but what could be better, is just to add their main logo, which would be better I think for this purpose, what do you think ?
> 
> ![the main logo](https://assets-eu-01.kc-usercontent.com/b1ac63b6-1e65-01f4-6f38-e97c0e9214a1/aedb7b5e-8556-4840-a69c-bce396891b0e/sonar-logo-horizontal-dark-bg.svg?w=170&h=42&auto=format&fit=crop)

This is also fine it seems, once added let me know.
Thanks 👍

**Comment by PritamChk** [comment]
@LelouchFR - it's not reflecting in my repo , I'm writing sonar

**Comment by ghost** [comment]
> @LelouchFR - it's not reflecting in my repo , I'm writing sonar

it's not yet added
