### ISSUE TITLE
[NEW ICON]: FrankenPHP

### ISSUE THREAD

**Issue by eng-gabrielscardoso** [LelouchFR/skill-icons#183]
### Skill Name

FrankenPHP

### Why?

Popular PHP app server

### Reference Image

![image](https://github.com/user-attachments/assets/781853f5-12c9-4841-bdd2-227926282f47)

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by Denisskas** [comment]
Svg Logo:
![frankenphp 6-min](https://github.com/user-attachments/assets/f7b1fef9-2256-466a-a8ac-ce625d584eaa)

**Comment by Denisskas** [comment]
@sckoorp I found better quality svg icon
![icon](https://github.com/user-attachments/assets/37f6aaca-377c-4b08-b211-d4fe92b0e57b)

**Comment by ghost** [comment]
> @sckoorp I found better quality svg icon ![icon](https://private-user-images.githubusercontent.com/110352433/369626870-37f6aaca-377c-4b08-b211-d4fe92b0e57b.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MzM0NzcsIm5iZiI6MTcyNjkzMzE3NywicGF0aCI6Ii8xMTAzNTI0MzMvMzY5NjI2ODcwLTM3ZjZhYWNhLTM3N2MtNGIwOC1iMjExLWQ0ZmU5MmIwZTU3Yi5zdmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQxNTM5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDIyNTY0MDhjNGZjODk2MjhiMjY0MDAzZDAyMTQ4NGM1YjNjMzgxZmFmYTIzYjI1NDM1MWJkN2ZlNjdjNzAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ov_38bTrjqUtcL7lDGaPC7BcqPUS9TdcbgzoSo2UD94)

aight thanks <3
