### ISSUE TITLE
[NEW ICON]: PHPStan

### ISSUE THREAD

**Issue by eng-gabrielscardoso** [LelouchFR/skill-icons#184]
### Skill Name

PHPStan

### Why?

Static analysis tool for PHP code

### Reference Image

![image](https://github.com/user-attachments/assets/d1453e33-f2c7-453d-9613-3c260b66259e)

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
I don' find any svg of this logo :/

**Comment by ghost** [comment]
@LelouchFR let this to me, i found it
