### ISSUE TITLE
[NEW ICON]: LlamaIndex

### ISSUE THREAD

**Issue by LuluW8071** [LelouchFR/skill-icons#187]
### Skill Name

LlamaIndex

### Why?

Framework for building LLM applications. 

[Website Link](https://www.llamaindex.ai/)

### Reference Image

![image](https://github.com/user-attachments/assets/41dd09dd-d395-4239-8ede-f32216c89f3b)

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by Daynlight** [comment]
https://github.com/LelouchFR/skill-icons/blob/main/assets/llamaindex-auto.svg

**Comment by LelouchFR** [comment]
@LuluW8071 llamaindex is already in the project, I think there is only missing in the readme, strange, going to look into that, but still, the icon is useable, try things out before opening an issue, thanks :)

**Comment by LuluW8071** [comment]
Oh. Thanks for heads up
