### ISSUE TITLE
[NEW ICON]: SQLAlchemy

### ISSUE THREAD

**Issue by coren-frankel** [LelouchFR/skill-icons#190]
### Skill Name

SQLAlchemy

### Why?

It's a popular open source Python ORM and database toolkit.

The reference image comes from the avatar of the [SQLAlchemy github organization](https://github.com/sqlalchemy).

### Reference Image

![SQLAlchemy](https://avatars.githubusercontent.com/u/6043126?s=200&v=4)

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by NonsensicalOne** [comment]
Thank you for your contribution, but please, instead of putting PNGs, put SVG files instead, we don't accept PNGs and JPEGs.

For the OP, heres the SVG version:
![](https://upload.wikimedia.org/wikipedia/commons/d/d7/SQLAlchemy.svg)
