### ISSUE TITLE
[NEW ICON]: Thunkable

### ISSUE THREAD

**Issue by shreyas-a-s** [LelouchFR/skill-icons#200]
### Skill Name

Thunkable

### Why?

It's a very popular low-code editor with which we can make mobile apps without coding knowledge by dragging and dropping elements.

### Reference Image

PNG from their website ([link](https://thunkable.com/press)):
<img width="471" alt="thunkableLogo" src="https://github.com/user-attachments/assets/25d5118c-c814-44d9-805f-0a0e898a86cb">

SVG (Obtained by cropping and converting PNG):
![thunkable](https://github.com/user-attachments/assets/9b98dfaa-f8e9-46d9-95c2-d9495175b09f)

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
@shreyas-a-s I've sent a message to their team to see if it could be possible to get a svg version from them, since it would be a better quality than the generated one. Else yeah it's a very good idea, just having to wait for their response.

**Comment by Denisskas** [comment]
SVG version:
![thunkable](https://github.com/user-attachments/assets/e26f40b7-b719-41e4-b265-19b90a713c52)

**Comment by shreyas-a-s** [comment]
@Denisskas Cool. Where did you get it from, buddy?

**Comment by Denisskas** [comment]
@shreyas-a-s I found on this site: https://testrigor.com/blog/thunkable-testing/

**Comment by LelouchFR** [comment]
@shreyas-a-s @Denisskas I think, else we do a dark and light (and auto ofc) version, or just one single instance with the background color of the logo itself

this:

![image](https://github.com/user-attachments/assets/c6830a5a-e6a8-4baa-99ec-c48690a8c6c7)

or this:

![image](https://github.com/user-attachments/assets/701efeec-cf0f-481c-ba7d-ba01dcaf572e)

in my opinion the last one is better, let me know what you think

**Comment by shreyas-a-s** [comment]
I am also liking the second one better since there is a blend of the background color of image and the icon. It looks cleaner.
