### ISSUE TITLE
[NEW ICON]: Erlang

### ISSUE THREAD

**Issue by reiswindy** [LelouchFR/skill-icons#206]
### Skill Name

Erlang

### Why?

Erlang is a functional programming language created in 1986 by Ericsson. Erlang's runtime is known for its built-in support for concurrency, distribution and fault tolerance. Erlang's VM (BEAM) is also the underlying runtime for Elixir.

### Reference Image

![erlang](https://github.com/user-attachments/assets/f4ae4a43-1fb4-4faa-bf72-417fc92c51ab)

### Svg Availability

- [X] I have given the official svg version of the logo in the Reference Image field.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
@reiswindy I've been thinking doing this icons since a pretty long time, but never seem to be good :/

let me know what you think about this ?

![image](https://github.com/user-attachments/assets/d219b499-aa45-4ed2-8c45-8664e88d11e0)

I think it could be better but can't get it better myself :/
