### ISSUE TITLE
[NEW ICON]: MSSQL

### ISSUE THREAD

**Issue by dimitrov8** [LelouchFR/skill-icons#207]
### Skill Name

MSSQL

### Why?

MSSQL (Microsoft SQL Server) is a popular relational database management system developed by Microsoft. It is widely used for enterprise-level database solutions due to its performance, scalability, and extensive features. MSSQL supports a variety of data types, transaction management, and integration with other Microsoft products, making it a vital tool for developers and database administrators.

### Reference Image

![microsoft-sql-server-logo-svgrepo-com](https://github.com/user-attachments/assets/6ec144a2-c506-4700-b924-bfc867b67d80)

### Svg Availability

- [X] I have given the official svg version of the logo in the Reference Image field.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
please look at every single icon before opening an issue.

Use `sqlserver` to use the icon:

![icon](https://go-skill-icons.vercel.app/api/icons?i=sqlserver)
