### ISSUE TITLE
[NEW ICON]: Daisy UI

### ISSUE THREAD

**Issue by CroAnna** [LelouchFR/skill-icons#209]
### Skill Name

Daisy UI

### Why?

The most popular component library for Tailwind CSS

### Reference Image

https://img.daisyui.com/images/daisyui-logo/daisyui-logomark.svg

### Svg Availability

- [X] I have given the official svg version of the logo in the Reference Image field.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
have you looked at the available icons before opening issues ?

**Comment by CroAnna** [comment]
yeah, my bad
