### ISSUE TITLE
[FEAT]: Icon list in JSON format

### ISSUE THREAD

**Issue by CroAnna** [LelouchFR/skill-icons#212]
### Description

I would like to have JSON of all icons so I can use them more easily in my project (so I don't have to copy and paste all icon names one by one from the table of available icons). It should be updated after every icon list update.

### Additional Information

Something like:
[
  { icon: "-" },
  { icon: "acrobat" },
  { icon: "activitypub" },
  { icon: "actix" },
  { icon: "adonis" },
  { icon: "aero" },
...
]

### Code of Conduct Acknowledgment

- [x] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
to do this, you could simply do a script.

**Comment by CroAnna** [comment]
But why wouldn't you want to offer developers to simply use the icons? Maybe they don't want to import this project or know how to create scripts - just need the names of all icons to be able to dynamically show images on the webpage

**Comment by LelouchFR** [comment]
> But why wouldn't you want to offer developers to simply use the icons ?

a link isn't simple enough ? the point of it, is an **api** displaying an svg. I know it can be hard to know what are all the icons, but a simple

```bash
ls --ignore="*-dark.svg" --ignore="*-light.svg" assets | sed -e "s/-auto\.svg//g" -e "s/\.svg//g"
```

then you can search for the icon if needed.

> Maybe they don't want to import this project or know how to create scripts.

I don't really understand your point... a link, and it's all good, they don't know the name of their skill ? ... else it's our fault, else the skill isn't added already, else ...?

> just need the names of all icons to be able to dynamically show images on the webpage

at what moment you want to take all the icons ?
