### ISSUE TITLE
[NEW ICON]: Mistral and Claude

### ISSUE THREAD

**Issue by Francois-lenne** [LelouchFR/skill-icons#213]
### Skill Name

Mistral & Claude

### Why?

Both are popular LLM alongside chat GPT 

Le chat  --> https://mistral.ai/fr/

Claude by Antrhopic --> https://www.anthropic.com/

### Reference Image

![mistral-ai_logo](https://github.com/user-attachments/assets/a1e64f6f-1d87-4087-98c9-cc5746d0f83c)

![claude-ai](https://github.com/user-attachments/assets/e34b3a4c-0c4d-410b-9789-1a4665f1d56f)

### Svg Availability

- [X] I have given the official svg version of the logo in the Reference Image field.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
@Francois-lenne what do you think about this for claude, I don't know which one is better, with or without text ?

![image](https://github.com/user-attachments/assets/611d7c95-e974-47b2-8194-c156b316b249)

and for mistral, I think this should be good:

![image](https://github.com/user-attachments/assets/173ec50d-ed25-4948-87a7-75c14b42d083)

**Comment by Francois-lenne** [comment]
Hey @LelouchFR i think the one with the text is better 😉
