### ISSUE TITLE
[FEAT]: linkedin

### ISSUE THREAD

**Issue by isiahzac** [LelouchFR/skill-icons#220]
### Description

Maybe it's just my perception, but the corners of the linkedin icon look strange, they look white.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
You're right, just checked it, it has a white filled rect behind the blueish one, I'm going to fix it :)

**Comment by isiahzac** [comment]
That would be nice :). Thanks for your work, the icons are fire.
