### ISSUE TITLE
[NEW ICON]: Spring Boot

### ISSUE THREAD

**Issue by Timasostima** [LelouchFR/skill-icons#221]
### Skill Name

springboot

### Why?

Spring Boot is a tool that makes developing web applications and microservices with Spring Framework faster and easier.

### Reference Image

![spring-boot](https://github.com/user-attachments/assets/a7b328b1-58d0-40c6-9a1b-36b495870fa4)

### Svg Availability

- [ ] I have given the official svg version of the logo in the Reference Image field.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
by looking at the icons for the repository (https://github.com/spring-projects/spring-boot), I see that there is no real logo for it, but just that they use the spring-project logo, which you can already get on the repository using the keyword `spring`.
