### ISSUE TITLE
[NEW ICON]: JAX: numpy-like library with accelerator supported 

### ISSUE THREAD

**Issue by triilman25** [LelouchFR/skill-icons#225]
### Skill Name

JAX 

### Why?

JAX is a new library in mathematical computing and it is also called ML framework. JAX support common accelerator for boost mathematical computation like matrix multiplication (multi-dimension vector or multi-dimension tensor). In term as library, JAX is numpy-like library and has full support for numpy library.

### Reference Image

https://raw.githubusercontent.com/google/jax/main/images/jax_logo_250px.png
https://jax.readthedocs.io/en/latest/

### Svg Availability

- [x] I have given the official svg version of the logo in the Reference Image field.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by triilman25** [comment]
SVG file for JAX:
https://github.com/google/jax/blob/main/images/jax_logo.svg

**Comment by LelouchFR** [comment]
@triilman25 Do you think it will be okay if we just take off the strokes of the icon, like this:

![image](https://github.com/user-attachments/assets/6ca22a2d-02d3-4fae-9c62-626cee4ac535)

**Comment by triilman25** [comment]
I think it is okay.
