### ISSUE TITLE
[NEW ICON]: SOLANA and Blockchain Technologies

### ISSUE THREAD

**Issue by VegaHaxorOne** [LelouchFR/skill-icons#227]
### Skill Name

Solana Blockchain

### Why?

Well, it's Blockchain. This that i'm suggesting is the logo for the general technology
but it could be more specific for the Solana CLI or entire documentation which could be a green or green and black logo

CLI: For reference https://docs.solanalabs.com/cli

### Reference Image

![solanaLogoMark](https://github.com/user-attachments/assets/630671e8-31aa-4bf5-b191-b587c8b8a2c8)

### Svg Availability

- [X] I have given the official svg version of the logo in the Reference Image field.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by Denisskas** [comment]
![solana-blockchain-dark](https://github.com/user-attachments/assets/2407c367-5e51-4987-ae6f-700a2000c8b0)
![solana-blockchain-dark](https://github.com/user-attachments/assets/bd5bece8-16ab-4db0-b591-088f8e51e1d7)
![solana-blockchain-light](https://github.com/user-attachments/assets/02b70da3-7f91-4f6e-abf8-61f2eed7416d)

**Comment by VegaHaxorOne** [comment]
To update this, do i just need to add these svg and update the table of the readme? If so i have the fork ready to be reviewed for the pull @LelouchFR

**Comment by LelouchFR** [comment]
> To update this, do i just need to add these svg and update the table of the readme? If so i have the fork ready to be reviewed for the pull @LelouchFR

Pretty much, but I will for sure ask some changes about the architecture of the svg, or some other things :)

**Comment by VegaHaxorOne** [comment]
Yeah, might be the case. It's my first time working with svg. I'll go for the request then

**Comment by LelouchFR** [comment]
pushed to main in #231
