### ISSUE TITLE
[NEW ICON]: Metabase

### ISSUE THREAD

**Issue by Francois-lenne** [LelouchFR/skill-icons#228]
### Skill Name

Metabase

### Why?

It's a popular open source visualisation tools use in licorn like doctolib 

--> https://github.com/metabase/metabase 

### Reference Image

![metabase-auto](https://github.com/user-attachments/assets/9599d0a3-6fe7-4b39-ac8f-c50c2b5d83ca)
![metabase-dark](https://github.com/user-attachments/assets/06d131cb-baf5-42b3-bfe8-542fdd458db2)
![metabase-light](https://github.com/user-attachments/assets/67d55960-c310-43e8-9774-1c7615e2435b)

### Svg Availability

- [X] I have given the official svg version of the logo in the Reference Image field.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by Francois-lenne** [comment]
hi @LelouchFR i add another icon can you add it to the main ?

**Comment by LelouchFR** [comment]
@Francois-lenne Sure, I'm going to look forward into it :)

**Comment by Francois-lenne** [comment]
@LelouchFR  thanks a lot 🚀
