### ISSUE TITLE
[NEW ICON]: Expo

### ISSUE THREAD

**Issue by RushilJalal** [LelouchFR/skill-icons#229]
### Skill Name

Expo

### Why?

Expo is the most popular framework to create mobile apps in React Native

### Reference Image

![banner](https://github.com/user-attachments/assets/27a4e79c-5029-4e9d-8adb-327b2af02e37)

### Svg Availability

- [ ] I have given the official svg version of the logo in the Reference Image field.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by Denisskas** [comment]
Logos: https://expo.dev/brand
