### ISSUE TITLE
[NEW ICON]: Twig

### ISSUE THREAD

**Issue by LelouchFR** [LelouchFR/skill-icons#230]
### Skill Name

Twig

### Why?

Twig is a template engine for php with a lot of features.

### Reference Image

![](https://twig.symfony.com/images/logo.md.png)

### Svg Availability

- [ ] I have given the official svg version of the logo in the Reference Image field.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by Denisskas** [comment]
Svg Icon: 
![201967141-2ff5b415-d9ac-4b45-81fb-9fcdcf7968d0](https://github.com/user-attachments/assets/8c93316b-0f99-400a-a0b7-56be362c9e65)
Source:https://github.com/twigphp/Twig/issues/2347
