### ISSUE TITLE
[BUG]: Telegram icon not working

### ISSUE THREAD

**Issue by RushilJalal** [LelouchFR/skill-icons#236]
### Description of the bug

The icon doesn't work properly and only displays a blue bg.
![image](https://github.com/user-attachments/assets/8401251c-34ed-4f2b-bad4-cc8857e370ad)

### Steps To Reproduce

1. View the icon in the .md file of the repo

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
Well, seems like I'm not the only one :P @IPdotSetAF 

I'm going to look into it asap

**Comment by IPdotSetAF** [comment]
Thats weird.
Maybe i did something wrong when modifying the svg code that makes it not render on some browsers.

**Comment by IPdotSetAF** [comment]
does this one display correctly @RushilJalal @LelouchFR ?

![telegram](https://raw.githubusercontent.com/IPdotSetAF/skill-icons/telegram-icon/assets/telegram.svg)

**Comment by RushilJalal** [comment]
@IPdotSetAF shouldn't the icon be much smaller?
The icon looks fine to me until I click on the icon which only shows a black box
![image](https://github.com/user-attachments/assets/28678936-c81b-477c-ade9-7b436a2960a5)

**Comment by IPdotSetAF** [comment]
@RushilJalal what is your browser/device
The size doesn't matter.
But the black box is new😅

ps: seems like the URL was broken, check again I updated it.

**Comment by LelouchFR** [comment]
@IPdotSetAF  what software are you using to make the icon ?

**Comment by RushilJalal** [comment]
@IPdotSetAF I am using Firefox on Windows 11 laptop.
Yep, clicking it works for me now.

**Comment by IPdotSetAF** [comment]
> @IPdotSetAF what software are you using to make the icon ?

Adobe illustrator

**Comment by IPdotSetAF** [comment]
@LelouchFR just found out that Firefox has a problem rendering some SVG images, I faced the same problem today in [NeoMatrix](https://ipdotsetaf.github.io/NeoMatrix)
