### ISSUE TITLE
[NEW ICON]: GDevelop

### ISSUE THREAD

**Issue by RushilJalal** [LelouchFR/skill-icons#237]
### Skill Name

GDevelop

### Why?

It's a popular beginner friendly no-code game engine

### Reference Image

![image](https://github.com/user-attachments/assets/6c4b38c7-304f-4da4-8314-e7d03f0c9677)

### Svg Availability

- [ ] I have given the official svg version of the logo in the Reference Image field.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by Denisskas** [comment]
Svg Logo:
![GDevelop_complete_logo_(purple_background)](https://github.com/user-attachments/assets/23e2cd20-3964-43b3-add0-5c1ef226ab09)

**Comment by RushilJalal** [comment]
@Denisskas Thank you for sharing the SVG logo.
I am looking to only having the 'G' in the icon tho.
