### ISSUE TITLE
[NEW ICON]: Argo CD

### ISSUE THREAD

**Issue by jacobjlee** [LelouchFR/skill-icons#24]
### Skill Name

Argo CD

### Why?

A popular tool for GitOps CD.
(Thank you for your work! glad to use many many icons here 😄)
https://techicons.dev/icons/argocd

### Reference Image

![image](https://github.com/LelouchFR/skill-icons/assets/71483710/7e004c3a-afa6-47e5-a5f8-ec453d68fe12)

**Comment by LelouchFR** [comment]
Sure I'm going to work on it! Thank you for your support, got some interesting features comming in the project as soon as I have finished "remaking" all the icons (a possibility to set the theme to auto)
