### ISSUE TITLE
[FEAT]: Update Powershell icon

### ISSUE THREAD

**Issue by CrazyWolf13** [LelouchFR/skill-icons#241]
### Description

Thanks for maintaining this much better version!

Do you consider adding the new powershell core icon?
Found this Image, here it's quickly visible what the differences are.

https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.it-connect.fr%2Fwp-content-itc%2Fuploads%2F2021%2F04%2Fslide-windows-powershell-vs-powershell-core-2021-768x427.jpg&f=1&nofb=1&ipt=fd44aabe11443abfea525a25e1a157977e8cbcec0cc882fc606d9aefb4f5a0de&ipo=images

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
same reasons then #242
