### ISSUE TITLE
[FEAT]: Android

### ISSUE THREAD

**Issue by CrazyWolf13** [LelouchFR/skill-icons#242]
### Description

Can't believe it, but is there no android icon yet?

If there is not yet one, I think it'd a good feature request :)

### Code of Conduct Acknowledgment

- [ ] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
Please, for an Icon suggestion, check before opening an issue, and use issue template made for it, thank you (read the code of conduct, really)

**Comment by CrazyWolf13** [comment]
- I have use the template
- There has not been any suggestion for Android Icon, there was one for Android Studio, but that is a different thing.

**Comment by LelouchFR** [comment]
I get it, but, reopen an issue with the right template... it's for an icon, please use the icon once, thanks
