### ISSUE TITLE
[NEW ICON]: Qdrant

### ISSUE THREAD

**Issue by simonwei97** [LelouchFR/skill-icons#244]
### Skill Name

Qdrant, Weaviate

### Qdrant

_**Qdrant**_ (read: quadrant) is a vector similarity search engine and vector database. 

- https://github.com/qdrant/qdrant

### Weaviate

_**Weaviate**_ is an open-source vector database that stores both objects and vectors, allowing for the combination of vector search with structured filtering with the fault tolerance and scalability of a cloud-native database​.

- https://github.com/weaviate/weaviate

### Qdrant

|  No  | URL     |Image     |
|:---:  | :-------: |:-------: |
| 1 | https://github.com/qdrant/qdrant/raw/master/docs/logo.svg | ![](https://github.com/qdrant/qdrant/raw/master/docs/logo.svg)| 
| 2 | https://qdrant.tech/img/logo.png | ![](https://qdrant.tech/img/logo.png) |

### Weaviate

|  No  | URL     |Image     |
|:---:  | :-------: |:-------: |
| 1 |  https://avatars.githubusercontent.com/u/37794290?s=48&v=4 |![](https://avatars.githubusercontent.com/u/37794290?s=48&v=4) |
| 2 | https://imgee.s3.amazonaws.com/imgee/e933221ebd4a4ea787ce65c6e3f56787_w240_h239.png  |![](https://imgee.s3.amazonaws.com/imgee/e933221ebd4a4ea787ce65c6e3f56787_w240_h239.png) |

### Svg Availability

- [X] I have given the official svg version of the logo in the Reference Image field.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by Denisskas** [comment]
Weaviate
Svg Logo:
![weaviate2023](https://github.com/user-attachments/assets/f3108942-4475-4dd2-8cdf-324bf7793762)

**Comment by LelouchFR** [comment]
@simonwei97 @Denisskas What do you guys think about this ?

qdrant:
![image](https://github.com/user-attachments/assets/0631d889-74d2-4a45-9bda-63a13dbe4386)

weaviate:
![image](https://github.com/user-attachments/assets/d2a94173-fb3c-4584-a9f1-50b2308365e0)

**Comment by Denisskas** [comment]
I think these icons look nice! 👍

**Comment by simonwei97** [comment]
Wonderful !

**Comment by LelouchFR** [comment]
I think because of the weaviate problem, I'm going to open another issue for it, so I can close this one on the PR so it's all easy, because it's blocking a little bit the continuity of the project
