### ISSUE TITLE
[NEW ICON]: Android

### ISSUE THREAD

**Issue by CrazyWolf13** [LelouchFR/skill-icons#245]
### Skill Name

android

### Why?

There is not an android-os icon available, that would be a really nice addition.

Thanks again for maintaining this projecl, and apologies again for selecting the wrong template!

### Reference Image

https://developer.android.com/static/images/brand/Android_Robot.svg

### Svg Availability

- [X] I have given the official svg version of the logo in the Reference Image field.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
what do you think about this ?

![image](https://github.com/user-attachments/assets/29f94da8-d960-4b7a-bbd4-2cec2cbe8270)

**Comment by CrazyWolf13** [comment]
That looks amazing!

Thanks a lot!
