### ISSUE TITLE
[NEW ICON]: Some suggested icons

### ISSUE THREAD

**Issue by isiahzac** [LelouchFR/skill-icons#25]
### Skill Name

GSAP, Jira and Zoom 

### Why?

They are now widely used tools and Gsap is one of the most widely used libraries at the moment.

### Reference Image

![gsap](https://github.com/LelouchFR/skill-icons/assets/130514737/535957b5-5ca2-423f-881f-c971a8c3e3a6)
![jira](https://github.com/LelouchFR/skill-icons/assets/130514737/67a7f01f-2cdf-4076-838d-30f42e0ff7e2)
![zoom](https://github.com/LelouchFR/skill-icons/assets/130514737/31552acb-22dc-4bf1-9008-646a77864317)

**Comment by LelouchFR** [comment]
I see some logic about Gsap and Jira, but what is zoom adding to it, as developer ?

**Comment by isiahzac** [comment]
Great question, it doesn't make sense. I was just missing Zoom because I've been using it for a long time :)

**Comment by LelouchFR** [comment]
Yeah actually now wrong that it is a tool, my bad, but for a logo, finding like a short type of icon for zoom, idk I'm going to look into that :)

**Comment by isiahzac** [comment]
Nice! I appreciate it.

**Comment by LelouchFR** [comment]
Hey @isiahzac, what do you think about this ? (don't worry, the icons are pngs here, because of github doing there stuff you know)

![image](https://github.com/LelouchFR/skill-icons/assets/75901978/bbd5c3ef-7ffa-4d00-a0a2-898ea4484340)

**Comment by isiahzac** [comment]
They look pretty nice, I like the GSAP one. Good job!
