### ISSUE TITLE
[NEW ICON] Laravel Orchid

### ISSUE THREAD

**Issue by eng-gabrielscardoso** [LelouchFR/skill-icons#251]
### Skill Name

Orchid

### Why?

Laravel panel builder

### Reference Image

![16124498](https://github.com/user-attachments/assets/c8b4166b-e48c-4ab1-8dc7-ccb4bd4e4148)

### Svg Availability

- [X] I have given the official svg version of the logo in the Reference Image field.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by Denisskas** [comment]
Example
![55573a2f-1bea-4321-9daa-c04353ef0a41 1](https://github.com/user-attachments/assets/5fbe2be3-706b-4ee5-8cda-cafc96ffc4f5)
