### ISSUE TITLE
[NEW ICON]: Zen Browser

### ISSUE THREAD

**Issue by Denisskas** [LelouchFR/skill-icons#255]
### Skill Name

zen, zenbrowser

### Why?

Zen browser based on Firefox, open-source, prioritizes security and privacy.

### Reference Image

![zen-black 2](https://github.com/user-attachments/assets/0e2596e0-5a93-486b-b124-c8cfd188a94f)

### Svg Availability

- [X] I have given the official svg version of the logo in the Reference Image field.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
what do you think about this ?

![image](https://github.com/user-attachments/assets/a9b2b74e-8129-4634-869a-f694f735e4d9)

**Comment by Denisskas** [comment]
@LelouchFR  Excellent!
