### ISSUE TITLE
[NEW ICON]: Revolt

### ISSUE THREAD

**Issue by KrystalSkullOfficial** [LelouchFR/skill-icons#259]
### Skill Name

Revolt

### Why?

Its a chatting app more or less like discord

https://revolt.chat/
https://github.com/revoltchat

### Reference Image

![356850850-c847559b-4b4f-44b2-9f97-6b518139475f](https://github.com/user-attachments/assets/6141cf54-d7b0-447c-8b6f-9be82f96cc32)

### Svg Availability

- [X] I have given the official svg version of the logo in the Reference Image field.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by Denisskas** [comment]
Example
![365388505-9b6e8d14-560e-4800-b707-ec255329f161 7](https://github.com/user-attachments/assets/14899c02-f935-4fa8-9421-ced22400b2c5)
