### ISSUE TITLE
[NEW ICON]: Apidog

### ISSUE THREAD

**Issue by LeleDallas** [LelouchFR/skill-icons#261]
### Skill Name

Apidog

### Why?

Similar to postman but with more features 
<img width="919" alt="Screenshot 2024-10-01 alle 12 47 28" src="https://github.com/user-attachments/assets/70ab6c81-18d2-4de8-bae0-04be0dd162da">

https://apidog.com/

### Reference Image

https://assets.apidog.com/static/logo/favicon.ico

### Svg Availability

- [X] I have given the official svg version of the logo in the Reference Image field.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by Denisskas** [comment]
@LeleDallas What do you think about this?
![a1ac5ccd-9178-4aa2-a73b-0e8fcd2212c8 4](https://github.com/user-attachments/assets/5db71574-dedf-4c9d-b4d6-174bf53aff99)

**Comment by LeleDallas** [comment]
> @LeleDallas What do you think about this?
> ![a1ac5ccd-9178-4aa2-a73b-0e8fcd2212c8 4](https://github.com/user-attachments/assets/5db71574-dedf-4c9d-b4d6-174bf53aff99)
> 

Perfect! 🔝
