### ISSUE TITLE
[NEW ICON]: Azure DevOps

### ISSUE THREAD

**Issue by avirgos** [LelouchFR/skill-icons#263]
### Skill Name

Azure DevOps 

### Why?

Platform used by many companies as a local GitHub and for project management, for example.

You can give it the following name : ```azdevops```

### Reference Image

![azdevops](https://github.com/user-attachments/assets/2d3b5d8a-7236-4875-a8c2-38b119095930)

### Svg Availability

- [X] I have given the official svg version of the logo in the Reference Image field.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by ghost** [comment]
Already available: https://go-skill-icons.vercel.app/api/icons?i=azuredevops

![](https://go-skill-icons.vercel.app/api/icons?i=azuredevops)
