### ISSUE TITLE
[NEW ICON]: Avalonia UI

### ISSUE THREAD

**Issue by Dynesshely** [LelouchFR/skill-icons#271]
### Skill Name

Avalonia UI

### Why?

It's a free open-source UI framework which is popular among dotnet developers.
We can use C# / F# to write Desktop / Mobile applications with this framework.

### Reference Image

![image](https://github.com/user-attachments/assets/fced2bb3-f1e6-4910-bc75-23cb72d832c3)

### Svg Availability

- [ ] I have given the official svg version of the logo in the Reference Image field.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by Denisskas** [comment]
Svg version:
![Group2](https://github.com/user-attachments/assets/bac5c766-ffc4-460a-a7df-a08334050247)

**Comment by Dynesshely** [comment]
> Svg version: ![Group2](https://private-user-images.githubusercontent.com/110352433/377135078-bac5c766-ffc4-460a-a7df-a08334050247.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwOTYzNjAsIm5iZiI6MTcyOTA5NjA2MCwicGF0aCI6Ii8xMTAzNTI0MzMvMzc3MTM1MDc4LWJhYzVjNzY2LWZmYzQtNDYwYS1hN2RmLWEwODMzNDA1MDI0Ny5zdmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQxNjI3NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmYyYTRhNGZiYmQzYTE0MzRkYzdiMzFjZjE2OWExYTdjOTIyNTdlNmJiOTMyNzEzOWYwNGU5ODNjMWU2NzhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._XEzL_HfWLMHFZvtp5dlAQc0298gbfccUNHL62sxTg4)

It's good, and avalonia ui also owns a colored version which could be nice to display in readme
![image](https://github.com/user-attachments/assets/2c5448a8-3b12-42ff-9bce-44cf310705aa)
