### ISSUE TITLE
[NEW ICON]: DigitalOcean

### ISSUE THREAD

**Issue by islandboymv** [LelouchFR/skill-icons#28]
### Skill Name

DigitalOcean

### Why?

1. Popularity and Usage: DigitalOcean is a widely used cloud infrastructure provider, known for its simplicity and robust features. It is popular among developers, startups, and enterprises for deploying and scaling applications.
2. Developer Community: DigitalOcean has a strong and growing developer community. Including the DigitalOcean icon will benefit many developers who use this platform and want to showcase their skills and tools.
3. Consistency and Completeness: The skill-icons repository aims to provide a comprehensive set of icons for various tools and technologies. Including the DigitalOcean icon helps in maintaining the completeness of this repository, as it is one of the major players in the cloud infrastructure space alongside AWS, Google Cloud, and Microsoft Azure.

### Reference Image

![DigitalOcean-Dark](https://github.com/LelouchFR/skill-icons/assets/90321630/cf5d172b-5afe-4843-97d6-ebcbfe7c7c21)
![DigitalOcean-Light](https://github.com/LelouchFR/skill-icons/assets/90321630/54bc13d2-3cf1-4e91-af99-9a4b286d28cd)

**Comment by LelouchFR** [comment]
Going to work on it asap !
