### ISSUE TITLE
[NEW ICON]: Bluesky

### ISSUE THREAD

**Issue by byeoon** [LelouchFR/skill-icons#285]
### Skill Name

Bluesky

### Why?

Alternate to twitter, planning on putting it on my website

### Reference Image

https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg

### Svg Availability

- [X] I have given the official svg version of the logo in the Reference Image field.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
@byeoon I'm going to work on it :)

**Comment by KrstlSkll69** [comment]
Hi bryoon... also im just bumping this because id love to see this logo

**Comment by LelouchFR** [comment]
> Hi bryoon... also im just bumping this because id love to see this logo

I have some stuff to do, but they're more than ready, not gonna be long, I may work on a PR tonight if I have time or even morning (I had a very busy week and am a little sick, but I'll try my best)
