### ISSUE TITLE
[NEW ICON]: GROMACS

### ISSUE THREAD

**Issue by patrickallanfaustino** [LelouchFR/skill-icons#296]
### Skill Name

gromacs

### Why?

A free and open-source software suite for high-performance molecular dynamics and output analysis.

### Reference Image

![gromacs](https://github.com/user-attachments/assets/4ced819d-19c8-4e94-9f56-7a9a2095f5ab)

### Svg Availability

- [X] I have given the official svg version of the logo in the Reference Image field.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by al42and** [comment]
Hi! FYI, the logo has been updated 3 years ago, and now look like this:

![gmx_falcon_blue](https://github.com/user-attachments/assets/2a9b4173-9513-45cb-942b-126d29a8c73e)


Different formats, including SVG, are available here: https://gitlab.com/gromacs/gromacs/-/tree/v2024.4/docs/reference-manual/plots/GMX_logos?ref_type=tags
