### ISSUE TITLE
[BUG]: fix failed

### ISSUE THREAD

**Issue by NonsensicalOne** [LelouchFR/skill-icons#3]
### Description of the bug

vercel not deploying bruh

### Steps To Reproduce

https://vercel.com/account/tokens

create a token from here (hope its unlimited)
go to your github repo >> settings >> secrets and variables

make a VERCEL_TOKEN with the token content

**Comment by NonsensicalOne** [comment]
@LelouchFR

**Comment by LelouchFR** [comment]
@hawl1 yup working on it
