### ISSUE TITLE
[NEW ICON]: helm , argocd

### ISSUE THREAD

**Issue by SHIVANIUM-GIT** [LelouchFR/skill-icons#302]
### Skill Name

DEVOPS

### Why?

it is part of the devOps

### Reference Image

helm: https://www.svgrepo.com/svg/306187/helm

agroCD :  https://techicons.dev/icons/argocd

### Svg Availability

- [ ] I have given the official svg version of the logo in the Reference Image field.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
These icons are already in the project, please look carefully before opening an issue :)

**Comment by SHIVANIUM-GIT** [comment]
@LelouchFR may be api it does not work with link
```bash
<img src="https://skillicons.dev/icons?i=helm-light>
```

**Comment by LelouchFR** [comment]
> @LelouchFR may be api it does not work with link
> 
> ```bash
> 
> <img src="https://skillicons.dev/icons?i=helm-light>
> 
> ```
> 
> 
> 
> 

Have you read the documentation ?
