### ISSUE TITLE
[NEW ICON]: Synk

### ISSUE THREAD

**Issue by aramos20** [LelouchFR/skill-icons#304]
### Skill Name

Snyk

### Why?

its very popular for security

### Reference Image

![image](https://github.com/user-attachments/assets/2b09b203-e560-459a-9385-4adee2765ee7)

### Svg Availability

- [ ] I have given the official svg version of the logo in the Reference Image field.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by avirgos** [comment]
@aramos20 

It is already available. Check the `README.md` of this repo and you will find `snyk` icon.

**Comment by aramos20** [comment]
oof mb u right
