### ISSUE TITLE
[NEW ICON]: Pyxel

### ISSUE THREAD

**Issue by LelouchFR** [LelouchFR/skill-icons#36]
### Skill Name

Pyxel

### Why?

[Pyxel](https://github.com/kitao/pyxel/) is an open source python library for retro game development (because of only having 16 colors and pixel art), made by @kitao .

### Reference Image

![pyxel_logo_152x64](https://github.com/LelouchFR/skill-icons/assets/75901978/07e93782-7a0c-4519-97e6-7917413f11be)

**Comment by NonsensicalOne** [comment]
made a svg version through [here](https://codepen.io/shshaw/pen/XbxvNj)

![331811218-07e93782-7a0c-4519-97e6-7917413f11be](https://github.com/LelouchFR/skill-icons/assets/126889064/be36b0ba-fe9a-4c6d-a362-41990f79dd99)

**Comment by LelouchFR** [comment]
I've done this

![image](https://github.com/LelouchFR/skill-icons/assets/75901978/3af8af6b-732e-40bd-bf06-0cdb304c6526)
