### ISSUE TITLE
[NEW ICON]: Miro

### ISSUE THREAD

**Issue by ghost** [LelouchFR/skill-icons#40]
### Skill Name

Miro

### Why?

Miro is a really popular productivity tool for collaboration, diagramming, whiteboarding, etc.

### Reference Image

![image](https://github.com/LelouchFR/skill-icons/assets/66195939/8817f3ec-0b33-4de4-b5e6-e58692b2ed23)

**Comment by LelouchFR** [comment]
okay, sure ! going to work on that :)
