### ISSUE TITLE
[NEW ICON]: Clist.by

### ISSUE THREAD

**Issue by ghost** [LelouchFR/skill-icons#44]
### Skill Name

CLIST

### Why?

[clist.by](https://clist.by) is a popular site for people to track contests and ranking updates across various coding platforms.

### Reference Image

![clist](https://github.com/LelouchFR/skill-icons/assets/66195939/72303829-3dd8-4621-a634-89431aaee51c)

### Code of Conduct Aknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
Hi @qingy2019 I'm sorry but I don't really see why it's a skill ? I've looked at the site, and for me it seems pretty old.

**Comment by ghost** [comment]
Ok, I guess it's more of like a tool :/
