### ISSUE TITLE
[BUG]: Pull Request Template

### ISSUE THREAD

**Issue by LelouchFR** [LelouchFR/skill-icons#52]
### Description

It would be interesting, like @josemateuss suggested in #51 to make a PR Template to make life easier for reviewers and contributors to work in the project.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by josemateuss** [comment]
Nice @LelouchFR, I'll send a template suggestion in a few hours.

**Comment by josemateuss** [comment]
@LelouchFR I was thinking in something like this:
References: [creating-a-pull-request-template-for-your-repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
Please, help me with some ideas \o/

-------

## Add: <icon_name> icon

#### Issue related: #00

### Description:
Type here a brief description of the icon you are adding.

Icon ID | Dark | Light
-- | -- | --
<icon_id> | <icon_dark> | <icon_light>

**Comment by LelouchFR** [comment]
I was more thinking about something where you choose, if its an icon where there is a dark and light theme, or just one icon

then, if it's working on multiple icons, and giving the number in a box, to make it more readable

I mean, something that is pretty flexible, if you know what I mean. I'm searching if there is a way to make something like that rn

**Comment by josemateuss** [comment]
Got it, I'll make some researches also, I couldn't make this PR template using .yaml as it's possible in issues templates. Please, [take a look here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/using-query-parameters-to-create-a-pull-request) and see if you understand.

**Comment by josemateuss** [comment]
@LelouchFR with the templates in the main, have you seen if they are working?

**Comment by LelouchFR** [comment]
> @LelouchFR with the templates in the main, have you seen if they are working?

I could not choose any pull request template, I got put directly into a plain pull request...

**Comment by josemateuss** [comment]
I had done a lot of research on the internet and I understood that the only possible PR template was just one in the pull_request_template.md file, without being able to choose a template.

**Comment by LelouchFR** [comment]
> I had done a lot of research on the internet and I understood that the only possible PR template was just one in the pull_request_template.md file, without being able to choose a template.

Opened a Discussion in github community (https://github.com/orgs/community/discussions/127219)
