### ISSUE TITLE
⚠️ Release site not found ⚠️

### ISSUE THREAD

**Issue by LeleDallas** [LelouchFR/skill-icons#53]
### Description of the bug

If you check the release link [go-skill-icons.vercel.app](https://go-skill-icons.vercel.app/) you can see that it throws 404

### Steps To Reproduce

Just open  [go-skill-icons.vercel.app](https://go-skill-icons.vercel.app/) 

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
well... it's not really a bug :/ it's normal
