### ISSUE TITLE
[NEW ICON]: SVN

### ISSUE THREAD

**Issue by alfjl** [LelouchFR/skill-icons#56]
### Skill Name

SVN (Apache Subversion)

### Why?

Still used in different companies around the world.

### Reference Image

https://upload.wikimedia.org/wikipedia/commons/2/22/Apache_Subversion_logo.svg

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
I'm going to search a way to make an integration for this icon

**Comment by alfjl** [comment]
Thank you.
