### ISSUE TITLE
[NEW ICON]: Some Blockchain technologies

### ISSUE THREAD

**Issue by UMMAN2005** [LelouchFR/skill-icons#57]
### Skill Name

Blockchain Development

### Why?

These skills are literally all that were used in modern industry for blockchain and smart contract development. Images are jpg and png, but I think can be converted to svg easily.

### Reference Image

Hardhat
![hardhat](https://github.com/LelouchFR/skill-icons/assets/137191653/7a746107-ec73-4ed9-af87-8207ecdf94de)

Truffle
![truffle](https://github.com/LelouchFR/skill-icons/assets/137191653/dbc6489e-a2cd-4446-9c68-a641015322c5)

Foundry
![foundry](https://github.com/LelouchFR/skill-icons/assets/137191653/39240d81-9095-4d76-b193-e24923a61314)

Ganache
![ganache](https://github.com/LelouchFR/skill-icons/assets/137191653/391d2fd8-183f-4c6c-b51f-7dec938f129a)

Brownie
![brownie](https://github.com/LelouchFR/skill-icons/assets/137191653/eb26ea67-ae81-4288-9550-66afe3d5bbe5)

Apeworx
![apeworx](https://github.com/LelouchFR/skill-icons/assets/137191653/e312d81e-6d29-4f3f-9a44-8e8c37425ce8)

Vyper
![vyper](https://github.com/LelouchFR/skill-icons/assets/137191653/589059f2-e3d5-48a5-8aed-be362a8f0e73)

Ethereum
![ethereum](https://github.com/LelouchFR/skill-icons/assets/137191653/4d89ca37-a963-499e-ae85-860ad16ec732)

Polygon
![polygon](https://github.com/LelouchFR/skill-icons/assets/137191653/46bc3d6d-271e-43d1-a05e-353b83773389)

Alchemy
![alchemy](https://github.com/LelouchFR/skill-icons/assets/137191653/2d5e9d1b-d949-4c72-815f-4eea807d8226)

Infura
![infura](https://github.com/LelouchFR/skill-icons/assets/137191653/bbd69c54-1852-4939-93c5-1575a2aac7b4)

Chainlink
![chainlink](https://github.com/LelouchFR/skill-icons/assets/137191653/5ece4ba9-5704-459f-931e-cf3185f50bf1)

OpenZeppelin
![openzeppelin](https://github.com/LelouchFR/skill-icons/assets/137191653/5418022d-92df-4386-b186-50d058d05174)

### Code of Conduct Acknowledgment

- [ ] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
going to work on those asap ;)

**Comment by LelouchFR** [comment]
@UMMAN2005 I'm sorry but I don't think I will do Chainlink, Polygon, ETH, Apeworx, Brownie nor Foundry...

**Comment by UMMAN2005** [comment]
I know maybe it is frustrating, but may I learn the reason of why?

**Comment by LelouchFR** [comment]
> I know maybe it is frustrating, but may I learn the reason of why?

The thing is that:

- Ethereum:  ETH is simply a currency, so I think I don't really think it has its place here (I know it can be furstrating), but in my vision, it would be like adding the euro symbol or the dollar sign...
- Chainlink: the Icon can be confusing for people not comming from that background, since it looks like a lot of other icons... I know it's not really a valuable reason for it, but idk :/
- Others: I made my resarches and did not find the icons to have some svg, and I don't see some of them going into a square since they circle based
