### ISSUE TITLE
[FEAT]: Icon categories

### ISSUE THREAD

**Issue by UMMAN2005** [LelouchFR/skill-icons#58]
### Description

All icons are listed in README.md file according to alphabet. But it is hard to someone to see which icons are available. It will be great if they are categorized like social, tools, frontend, backend, low-level, design, adobe and etc

### Code of Conduct Acknowledgment

- [ ] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
The thing is that, if we do by classification, I think people will take more time to search their icon than if it is alphabetically. If we do that, it will be harder to "sort" them if there are new icons that come... I think it is okay to not have them sorted in a way other than alphabetically

**Comment by UMMAN2005** [comment]
Yes, I am totally agree. However, there are some icons that I do not really expect to see. And when some new icons added, always look for all icons needed. Anyway, it is just a small feature. Not the end of the world!
