### ISSUE TITLE
[NEW ICON]: PyTorch Lightning ⚡, Pytorch Ignite, Pytorch Fastai and Mojo

### ISSUE THREAD

**Issue by LuluW8071** [LelouchFR/skill-icons#63]
### Skill Name

Lightning, Ignite, Fastai, Mojo

### Why?

3 Deep learning frameworks that provides high level of abstraction (similar to keras for Tensorflow)
While Mojo is new programming language has faster computational speed than python, rust

### Reference Image

![image](https://github.com/LelouchFR/skill-icons/assets/107304848/14da408c-8090-4ced-b506-7f6b65590cb6)
![image](https://github.com/LelouchFR/skill-icons/assets/107304848/5f730754-3fa9-44d4-8bac-5d5f0b0d49c5)
![image](https://github.com/LelouchFR/skill-icons/assets/107304848/1a75e8a3-4685-4733-ae2c-21c1d47416ee)
![image](https://github.com/LelouchFR/skill-icons/assets/107304848/73c49ba5-7971-4d16-880e-4586ddf110cf)

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
Hi @LuluW8071 I've been working on these icons, but I have a little issue for the naming, should they all include pytorch in it ? or can it be shorten to lightning, ignite ?

**Comment by LuluW8071** [comment]
> Hi @LuluW8071 I've been working on these icons, but I have a little issue for the naming, should they all include pytorch in it ? or can it be shorten to lightning, ignite ?

No you don't need to put pytorch...(framework)

Naming:
- Lightning
- Fastai
- Ignite
- Mojo
