### ISSUE TITLE
[NEW ICON]: TALLY Prime 

### ISSUE THREAD

**Issue by WorldOfDex** [LelouchFR/skill-icons#74]
### Skill Name

Tally Prime - Accountings

### Why?

its an indian based accounting software , so i need to add that in my profile and its too famous as same as sap https://tallysolutions.com/tally-prime/

### Reference Image

![Tally-Prime](https://github.com/LelouchFR/skill-icons/assets/152152174/c6df726d-1c0e-4021-aa51-b19aff293fd9)

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by josemateuss** [comment]
@LelouchFR I can make this icon if you agree.

**Comment by LelouchFR** [comment]
> @LelouchFR I can make this icon if you agree.

yes sure !

**Comment by josemateuss** [comment]
Which one do you prefer guys? As light and dark or just filled one? @LelouchFR @WorldOfDex 
<img width="639" alt="image" src="https://github.com/LelouchFR/skill-icons/assets/26313645/9cd52211-447c-411a-a654-d44ada4a96eb">

**Comment by atr321** [comment]
I liked the third one

**Comment by josemateuss** [comment]
> I liked the third one

So do I, I'll make the PR with the third one

**Comment by LelouchFR** [comment]
> > I liked the third one
> 
> So do I, I'll make the PR with the third one

sounds good to me :)

**Comment by WorldOfDex** [comment]
all of them
