### ISSUE TITLE
[NEW ICON]: Streamlit, Langchain, Seaborn, Gemini, PineconeVectorDB, Kaggle

### ISSUE THREAD

**Issue by LuluW8071** [LelouchFR/skill-icons#76]
### Skill Name

Streamlit, Langchain, Seaborn, Gemini, Pinecone, Kaggle

### Why?

- **Streamlit:** Faster and interactive web app framework
- **Langchain:** Framework to build applications using LLMs
- **Seaborn:** Better version of Matplotlib
- **Gemini:** A multimodal LLM developed by Google teams
- **Pinecone:** A vector database widely used in building machine learning models
- **Kaggle:**  An online community platform for data scientists and machine learning enthusiast. (Similar to github)

### Reference Image

![Streamlit](https://github.com/LelouchFR/skill-icons/assets/107304848/4808099d-8dc9-4cac-8d03-aebb3e22b33e)
![Langchain](https://github.com/LelouchFR/skill-icons/assets/107304848/28930bf1-1dd0-4cf0-ad90-35c8c6743519)
![Seaborn](https://user-images.githubusercontent.com/315810/92255199-f6707f80-ee9f-11ea-9b8d-182dba6a0c59.png)
![Gemini](https://github.com/LelouchFR/skill-icons/assets/107304848/22bedc01-bca2-46a5-b1dd-fce38d82f6ee)
![Pinecone](https://github.com/LelouchFR/skill-icons/assets/107304848/b41efc15-b498-42e5-b2db-4be1784b81c0)
![Kaggle](https://github.com/LelouchFR/skill-icons/assets/107304848/dadea1ba-ea27-4e01-9925-d07cc973864b)

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
I'm going to work on it, but I have a little problem with the lang chain icon, since it's just emojies, I d'ont really like the idea to add it (at least not that version)

**Comment by LuluW8071** [comment]
You can just keep the chain part 🔗 for langchain

**Comment by LelouchFR** [comment]
@LuluW8071 I found on their github, icons, that I just have and I'm going to post the result here so you can tell me what you think about.

**Comment by LelouchFR** [comment]
@LuluW8071 what do you think about that ?

![image](https://github.com/LelouchFR/skill-icons/assets/75901978/a0b7366c-e858-4eb5-802f-519f3ff1aebd)

**Comment by LuluW8071** [comment]
> ![image](https://private-user-images.githubusercontent.com/75901978/337272162-a0b7366c-e858-4eb5-802f-519f3ff1aebd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NzkwNTAsIm5iZiI6MTcxNzY3ODc1MCwicGF0aCI6Ii83NTkwMTk3OC8zMzcyNzIxNjItYTBiNzM2NmMtZTg1OC00ZWI1LTgwMmYtNTE5ZjNmZjFhZWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDEyNTkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMThkMDRjY2NhOGU3OTRjNGI2N2I0M2Y1ZmM5MmY0ZDA5MWMwZTM5ZjI3MTk2NmU1NzA5ZjQxNWQ5ZWRmN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IiPUIKYpQwMHhM34RgOlHXyPqzwJeRqLWHsjfPlZ9Sc)

Looks great 😊

**Comment by fernandogprieto** [comment]
@LelouchFR if you have time could you check the issues from skill icons original repo! please!

**Comment by 1chooo** [comment]
> @LuluW8071 what do you think about that ?
> 
> ![image](https://private-user-images.githubusercontent.com/75901978/337272162-a0b7366c-e858-4eb5-802f-519f3ff1aebd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NDM1MDksIm5iZiI6MTcxNzg0MzIwOSwicGF0aCI6Ii83NTkwMTk3OC8zMzcyNzIxNjItYTBiNzM2NmMtZTg1OC00ZWI1LTgwMmYtNTE5ZjNmZjFhZWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDEwNDAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1Njg5YzAwMDgyYjJlODU4MjRlMWExNjNkMGJlYTZiZGE1MDE1Yjg5NWZkNGMzOWQyNzU3YjVlZmYxM2RlY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DvTblXECHauwRgpy3rD4wh5_Ym_nb88gdci69sMvIc0)

That's amazing!!!
